<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
    <DocumentationFile />
    <IsPackable>false</IsPackable>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
    <LangVersion>latest</LangVersion>
		<OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Parsing\Resources\*.po" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Parsing\Resources\*.po" />
  </ItemGroup>

  <ItemGroup>
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
		<PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
		<PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MGR.PortableObject.Parsing\MGR.PortableObject.Parsing.csproj" />
  </ItemGroup>

</Project>
